en = ["Time flies",
      "Sleep over",
      "At all costs",
      "In no time",
      "Half-and-half",
      "Run away",
      "Be broke",
      "Feel blue",
      "Bring up",
      "All ears",
      "Play along",
      "Catch up",
      "Duty calls",
      "On the go",
      "Break up",
      "To pony up",
      "Dead duck",
      "Egghead",
      "A lame duck",
      "Put up with",
      "Down to earth",
      "Hang up",
      "Tough cookie",
      "Home truth",
      "Spill the beans",
      "Get by",
      "Give up",
      "Act out",
      "Donkey work",
      "White lie",
      "No buts",
      "Time flies",
      "As easy as pie",
      "Gut feeling",
      "Pie in the sky",
      "Carry on",
      "Buy some time",
      "In no time",
      "Burn bridges",
      "Hit the jackpot",
      "Time is money",
      "Give it a shot",
      "Have a heart",
      "Now or never"
      ]

ru = ["Время летит",
      "Ночёвка",
      "Любой ценой",
      "В мгновение ока",
      "Ни то ни сё",
      "Сбегать",
      "Быть 'на мели' (без денег)",
      "Тосковать",
      "Упоминать",
      "Весь во внимании",
      "Подыгрывать",
      "Догнать",
      "Долг зовет",
      "На ходу",
      "Расстаться, прекратить отношения",
      "Раскошелиться",
      "Гиблое дело",
      "Умник",
      "Неудачник",
      "Смириться",
      "Практичный",
      "Повесить трубку",
      "Хулиган",
      "Горькая правда",
      "Раскрыть секрет",
      "Сводить концы с концами",
      "Сдаваться",
      "Изображать, разыгрывать",
      "Скучная, монотонная работа",
      "Ложь во благо",
      "Никаких но",
      "Время летит",
      "Легче легкого",
      "Чувствовать нутром",
      "Пустые мечты",
      "Продолжать",
      "Выиграть время",
      "В мгновение ока",
      "Сжигать мосты",
      "Сорвать куш",
      "Время - деньги",
      "Дать шанс",
      "Имейте сердце",
      "Сейчас или никогда"
      ]